name: Hackathon Submission
description: Add a hackathon submission
title: "[Project]: "
labels: ["submission", "needreview"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for participating in the hackathon and creating your submission!
  - type: input
    id: name
    attributes:
      label: Name
      description: Enter your full name
      placeholder: First Name Last Name
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email Address
      description: Enter your email address
      placeholder: email@email.com
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Project Description
      description: What have you built during the hackathon?
      placeholder: The project I created is...
    validations:
      required: true
  - type: textarea
    id: inspiration
    attributes:
      label: Inspiration behind the Project
      description: What is the story behind this project? Why did you choose to work on this specific idea?
      placeholder: The reason I chose this idea/project was...
    validations:
      required: true
  - type: textarea
    id: functionality-used
    attributes:
      label: Functionality Used
      description: How have you built this project? Mention the Study Buddy | AI Assistant functionality you used to build your project
      placeholder: The functionality I used...
    validations:
      required: true
  - type: dropdown
    id: track
    attributes:
      label: Hackathon Track
      description: What hackathon track are you opting in?
      options:
        - Physical Sciences 
        - Life Sciences  
        - Humanities      
        - Everything Else (Interdisciplinary/Cross-disciplinary) 
    validations:
      required: true
  - type: input
    id: project-link
    attributes:
      label: Project Repo
      description: Share a public repo link of your project
      placeholder: https://github.com/uralstech/ezrSquared
    validations:
      required: false
  - type: input
    id: conversation-link
    attributes:
      label: Conversation Recording
      description: Share a publicly visible video to a recording of your conversation
      placeholder: https://www.youtube.com/watch?v=.....
    validations:
      required: false
  - type: input
    id: demo-link
    attributes:
      label: Demo Video/Photos
      description: Share a publicly visible demo video/photos link of your project
      placeholder: https://www.youtube.com/watch?v=.....
    validations:
      required: false
  - type: textarea
    id: anything-else
    attributes:
      label: Anything Else?
      description: Any other feedback, queries or information, you would like to share with us?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Rules and Code of Conduct
      description: By submitting this issue, you agree to follow our Rules and Code of Conduct.
      options:
        - label: I agree to follow this hackathon's Rules and Code of Conduct
          required: true
